variables:
  ENV_NAME: dev
  
dotnetrestapi-build:
  variables:
    BUILDER_IMAGE_NAME: $BUILDER_IMAGE_DOTNET_6
    APP: dotnetrestapi
  stage: build
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/ci-image.yml'
    strategy: depend
    
dotnetrestapi-deploy:
  variables:
    APP_TRIGGER: dotnetrestapi
  stage: deploy
  trigger:
    project: 'linfeng.song/services'
