{{- if .Value.blb.deploy }}
apiVersion: test.example.com/v1
kind: ExamLoadBalancer
metadata:
  name: "{{ Values.applicationName }}-blb"
  namespace: {{ .Values.namespace | quote }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  route: "{{ .Values.applicationName }}-route"
{{ end }}