{{- if .Values.route.deploy }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Values.applicationName }}-route"
  namespace: {{ .Value.namespace | quote }}
spec:
  host: "{{ .Values.applicationName }}-{{ .Value.namespace }}.{{ .Values.route.domain }}"
  to:
    kind: Service
    name: "{{ .Values.applicationName }}-service"
  port:
    targetPort: {{ .Values.service.port | quote }}
  tls:
    termination: passthrough
  wildcardPolicy: None
{{ end }}