spring:
  profile: bcp
  serverShutdown: graceful
  timeoutPerShutdownPhase: 20s
  applicationName: application

imagePullSecret:
  name: imagepullsecret

certs:
  mountPath: /etc/certs
  
esaas:
  volumeMountPath: /var/log/bcp-applications
  logFilePath: /var/log/bcp-applications/application.json

