apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-rest-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
  name: spring-rest-api
spec:            
  replicas: {{ .Values.springrestapi.replicas }}
  selector:
    matchLabels:
      app: spring-rest-api
  template:
    metadata:
      labels:
        app: spring-rest-api
        name: spring-rest-api
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: 1.0.0
    spec:
      containers:
      - image: "{{ .Values.springrestapi.image.name }}:{{ .Values.springrestapi.image.tag }}"
        imagePullPolicy: {{ .Values.springrestapi.image.pullPolicy }}
        ports:
        - containerPort: 8080
          hostPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        name: spring-rest-api
        livenessProbe:
          httpGet:
            path: /spring-rest-api/
            port: 8080
            scheme: {{ .Values.springrestapi.httpScheme }}
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /spring-rest-api/
            port: 8080
            scheme: {{ .Values.springrestapi.httpScheme }}
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          privileged: false
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: persistent-volume
          mountPath: /home/app/spring-rest-api/logs
          subPath: logs/$(POD_NAME}
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: spring-rest-api
