apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.container.app }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
  name: {{ .Values.container.name }}
spec:            
  replicas: {{ .Values.container.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.app }}
        name: {{ .Values.container.name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: 1.0.0
    spec:
      containers:
      - image: "{{ .Values.container.image.name }}:{{ .Values.container.image.tag }}"
        imagePullPolicy: {{ .Values.container.image.pullPolicy }}
        ports:
        - containerPort: 80
          hostPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        name: {{ .Values.container.name }}
        livenessProbe:
          httpGet:
            path: {{ .Values.container.path }}
            port: 80
            scheme: {{ .Values.container.httpScheme }}
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: {{ .Values.container.path }}
            port: 80
            scheme: {{ .Values.container.httpScheme }}
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          privileged: false
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: persistent-volume
          mountPath: /home/app/logs
          subPath: logs/$(POD_NAME}
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: "{{ .Values.container.name }}-pvc"
