variables:
  ENV_NAME: dev
  
httpdreact-build:
  variables:
    BUILDER_IMAGE_NAME: $BUILDER_IMAGE_NODE_20
    APP: httpdreact
  stage: build
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/ci-image.yml'
    strategy: depend
    
dotnetrestapi-deploy:
  variables:
    APP_TRIGGER: httpdreact
  stage: deploy
  trigger:
    project: 'linfeng.song/services'
