variables:
  CI_APP: springrestapi
  ENV_NAME: dev
  
include:
  - project: 'linfeng.song/gitlab-templates'
    file: '/templates/v1/bcp-ci-image.yml'

deploy:
  variables:
    CD_BCP_APP_TRIGGER: httpdreact
  stage: deploy
  trigger:
    project: 'linfeng.song/services'

    