variables:
  ENV_NAME: dev
  
springrestapi-build:
  variables:
    BUILDER_IMAGE_NAME: $BUILDER_IMAGE_JAVA_17
    APP: springrestapi
  stage: build
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/ci-image.yml'
    strategy: depend
    
dotnetrestapi-deploy:
  variables:
    APP_TRIGGER: springrestapi
  stage: deploy
  trigger:
    project: 'linfeng.song/services'
 