variables:
  BUILDER_IMAGE_NAME: $BUILDER_IMAGE_JAVA_17
  CI_APP: springrestapi
  ENV_NAME: dev

include:
  - project: linfeng.song/gitlab-templates
    file: templates/v1/bcp-ci-image.yml
    
deploy:
  variables:
    CD_BCP_APP_TRIGGER: springrestapi
  stage: deploy
  trigger:
    project: linfeng.song/services
    