apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.container.name }}-pv"
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ocs-storagecluster-cephfs
  hostPath:
    path: '/data/docker_volume'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.container.name }}-pvc"
  labels:
    pv: "{{ .Values.container.name }}-pv"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs
  