{{- if .Values.hpa.deploy }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.applicationName }}-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.applicationName }}-deployment"
  minReplicas: {{ .Values.hpa.minPods }}
  maxReplicas: {{ .Values.hpa.maxPods }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: utilization
          averageUtilization: {{ .Values.hpa.cpuUsage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: utilization
          averageUtilization: {{ .Values.hpa.memoryUsage }}
{{ end }}