variables:
  ENV_NAME: dev
  CD_BCP_APPS: httpdswag,springrestapi,dotnetrestapi,httpdreact
  
include:
  - project: 'linfeng.song/gitlab-templates'
    file: 'templates/v1/bcp-cd-container.yml'
    
spring-rest-api-deploy:
  extends: .deploy-cd-bcp-container
  variables:
    CD_BCP_APP: springrestapi
    
spring-rest-api-reload:
  extends: .reload-cd-bcp-container
  variables:
    CD_BCP_APP: springrestapi

dotnet-rest-api-deploy:
  extends: .deploy-cd-bcp-container
  variables:
    CD_BCP_APP: dotnetrestapi
    
dotnet-rest-api-reload:
  extends: .reload-cd-bcp-container
  variables:
    CD_BCP_APP: dotnetrestapi
    
httpd-react-deploy:
  extends: .deploy-cd-bcp-container
  variables:
    CD_BCP_APP: httpdreact
    
httpd-react-reload:
  extends: .reload-cd-bcp-container
  variables:
    CD_BCP_APP: httpdreact
