variables:
  ENV_NAME: dev
  APP_TRIGGER: ALL
  
spring-rest-api-deploy:
  variables:
    APP: springrestapi
  stage: deploy
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/bcp-container-deploy.yml'
    strategy: depend
  only:
    variables:
      - $APP_TRIGGER == "ALL"
    
spring-rest-api-reload:
  variables:
    APP: springrestapi
  stage: deploy
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/bcp-container-reload.yml'
    strategy: depend
  only:
    variables:
      - $APP_TRIGGER == $APP
    
dotnet-rest-api-deploy:
  variables:
   APP: dotnetrestapi
  stage: deploy
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/bcp-container-deploy.yml'
    strategy: depend
  only:
    variables:
      - $APP_TRIGGER == "ALL"
    
dotnet-rest-api-reload:
  variables:
    APP: dotnetrestapi
  stage: deploy
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/bcp-container-reload.yml'
    strategy: depend
  only:
    variables:
      - $APP_TRIGGER == $APP
    
httpd-react-deploy:
  variables:
    APP: httpdreact
  stage: deploy
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/bcp-container-deploy.yml'
    strategy: depend
  only:
    variables:
      - $APP_TRIGGER == "ALL"
    
httpd-react-reload:
  variables:
    APP: httpdreact
  stage: deploy
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/bcp-container-reload.yml'
    strategy: depend
  only:
    variables:
      - $APP_TRIGGER == $APP
    
