openshift_api_url: "https://api.%[cluster_name]%-%[datacenter]%.example.com"

ci:
  docker_image_registry: "example.registry-%[ci.registry_location]%.example.com"
  docker_image_name: "%[ci.docker_image_%[IMAGE_TYPE]%]%"
  docker_image_path: "%[ci.docker_image_name]%"
  registry_location: "%[ci.registry_location_%[ci.image_dest_env]%]%"
  docker_image_maven: "registry.access.redhat.com/ubi8/openjdk-17"
  docker_image_dotnet: "mcr.microsoft.com/dotnet/aspnet:6.0"
  docker_image_httpd: "httpd:2.4"
  registry_location_nonprod: np-v4-uk
  registry_location_us-nonprod: np-v4-us
  registry_location_ap-nonprod: np-v4-ap
  registry_location_prod: prod-v4-uk
  registry_location_us-prod: prod-v4-us
  registry_location_ap-prod: prod-v4-ap
