image: registry.access.redhat.com/ubi8/openjdk-17:1.19-1

variables:
  CI_BUILD_TYPE: jar
  CI_BUILD_TARGET_PATH: target/app.jar
  
stages:
  - build
  - test
  - docker
  - promote
  - deploy

include:
  - project: linfeng.song/gitlab-templates
    ref: master
    file: '/templates/v1/job/load-gitlab-utils.yml'
    
  - project: linfeng.song/gitlab-templates
    ref: master
    file: '/templates/v1/job/maven-jar.yml'
    
  - project: linfeng.song/gitlab-templates
    ref: master
    file: '/templates/v1/job/maven-test.yml'
    
  - project: linfeng.song/gitlab-templates
    ref: master
    file: '/templates/v1/job/docker-build.yml'
      