apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "ocs-storagecluster-cephfs"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "ocs-storagecluster-cephfs-pv"
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "ocs-storagecluster-cephfs"
  hostPath:
    path: '/data/docker_volume'
