apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.applicationName }}-map"
data:
  application-bcp.yml: |
    {{- if .Values.esaas.deploy }}
    logging:
      file:
        name: {{ .Values.esaas.logFilePath }}
    {{ end }}
    info:
      application:
        version: {{ .Values.image.tag }}
    spring:
      application:
        name: {{ .Values.spring.applicationName }}
      lifecycle:
        timeout-per-shutdown-phase: {{ .Values.spring.timeoutPerShutdownPhase }}
      management:
        endpoint:
          health:
            probes:
              enabled: true
            livenessState:
              enabled: true
            readinessState:
              enabled: true
    server:
      shutdown: {{ .Values.spring.serverShutdown }}
      port: {{ .Values.pod.port }}
      {{- if .Values.certs.deploy }}
      ssl:
        key-store-type: PKCS12
        key-store: {{ .Values.certs.mountPath }}/keystore.p12
        key-store-password: ${KEYSTORE_PASSWORD}
      {{ end }}
  {{- if .Values.esaas.deploy }}
  logback-spring.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
        <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
    
        <root level="INFO">
            <appender-ref ref="CONSOLE"/>
        </root>

        <springProfile name="bcp">
            <springProperty name="SERVICE_NAME" source="spring.application.name"/>
            <appender name="ECS_FILE" class="ch.qos.logback.core.FileAppender">
                <file>${LOG_FILE}</file>
                <encoder class="co.elastic.logging.logback.EcsEncoder">
                    <serviceName>${SERVICE_NAME}</serviceName>
                </encoder>
            </appender>
        
            <root>
                <appender-ref ref="ECS_FILE"/>
            </root>
        </springProfile>
    
    </configuration>  
  {{ end }}
