kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.esaas.logsPvcName }}
  namespace: {{ .Values.namespace | quote }}
  annotations:
    {{/*
    PVC will not be removed when the Helm release is uninstalled
    to reduce potential for log data loss
    */}}
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
