apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "application-logs-local-storage"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "application-logs-pv"
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "application-logs-local-storage"
  hostPath:
    path: '/data/docker_volume'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "application-logs-pvc"
  labels:
    pv: "application-logs-pv"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "application-logs-local-storage"
  resources:
    requests:
      storage: 1Gi
