variables:
  CD_BUILD_TYPE: container
  CONTAINER_NAME: change_me
  CONTAINER_TRIGGER: ALL

include:
  - project: 'dev/dev-java/gitlab_common'
    ref: master
    file: '/templates/v1/job/load_common_util.yml'

stages:
  - deploy
  
.reload-container-package:
  stage: deploy
  script:
    - |
      cd_common_path=$(pwd)/cd_common
      mkdir -p $cd_common_path
      tar xvf common_util.tar -C $cd_common_path
        
      $cd_common_path/script/containerRefresh.sh $CONTAINER_NAME
  only:
    variables:
      - $CONTAINER_TRIGGER == $CONTAINER_NAME
        
.deploy-container-package:
  stage: deploy
  script:
    - |
      cd_common_path=$(pwd)/cd_common
      mkdir -p $cd_common_path
      tar xvf common_util.tar -C $cd_common_path
      
      env_name=dev
      echo "create secret"
      whoami
      $cd_common_path/script/secret.sh httpd-swag certificate-pwd $CERTIFICATE_PWD
      echo "create tls"
      $cd_common_path/script/createTls.sh $CONTAINER_NAME/service_${env_name}.ini $cd_common_path/service/api/cert.yaml.template
      echo "deploy httpd-swag"
      echo $cd_common_path/script/helmDeploy.sh httpd-swag $cd_common_path/service/helm $cd_common_path/service/helm/values.yaml.template service env $CONTAINER_NAME/service_${env_name}.ini false
      $cd_common_path/script/helmDeploy.sh httpd-swag $cd_common_path/service/helm $cd_common_path/service/values.yaml.template service env $CONTAINER_NAME/service_${env_name}.ini false
      echo "finish deploy"
  only:
    variables:
      - $CONTAINER_TRIGGER == "ALL"
        