variables:
  GITLAB_UTILS_URL: "http://lenovo:50080/api/v4/projects/8/repository/archive.tar.gz?ref=master"
  GITLAB_UTILS_ACCESS_TOKEN: "PRIVATE-TOKEN: glpat-iN1x2--EsScyorcdaZt2"
  GITLAB_UTILS_PATH: "gitlab_utils"

stages:
  - .pre

load_gitlab_utils_job:
  stage: .pre
  script:
    - |
      echo "Load gitlab utils start"
      srcPath=$(pwd)
      echo curl -L --header "$GITLAB_UTILS_ACCESS_TOKEN" "$GITLAB_UTILS_URL" -o 'archive.tar'
      curl -L --header 'PRIVATE-TOKEN: glpat-W2z5-4YTb6CcnrLoijtU' 'http://lenovo:50080/api/v4/projects/8/repository/archive.tar?ref=master' -o 'archive.tar'
      tar xf archive.tar
      if [[ $? -ne 0 ]]; then
        cat archive.tar
        exit 1
      fi
      gitlab_utils_master_path=gitlab-utils-master
      mkdir -p $gitlab_utils_master_path/conf
      cp $gitlab_utils_master_path-*/conf/* $gitlab_utils_master_path/conf
      chmod 644 $gitlab_utils_master_path/conf/*
      mkdir -p $gitlab_utils_master_path/script
      cp $gitlab_utils_master_path-*/script/* $gitlab_utils_master_path/script
      chmod 755 $gitlab_utils_master_path/script/*
      mkdir -p $gitlab_utils_master_path/tool
      cp -R $gitlab_utils_master_path-*/tool/* $gitlab_utils_master_path/tool
      chmod 755 $gitlab_utils_master_path/tool/*
      if [[ ! -z $CI_BUILD_TYPE ]]; then
        mkdir -p $gitlab_utils_master_path/build
        cp -r $gitlab_utils_master_path-*/build/common/* $gitlab_utils_master_path/build
        cp -r $gitlab_utils_master_path-*/build/$CI_BUILD_TYPE/* $gitlab_utils_master_path/build
      elif [[ ! -z $CD_BUILD_TYPE ]]; then
        mkdir -p $gitlab_utils_master_path/infra
        cp -r $gitlab_utils_master_path-*/infra/$CD_BUILD_TYPE/* $gitlab_utils_master_path/infra
      fi
      cd $gitlab_utils_master_path
      tar cvf $srcPath/gitlab_utils.tar *
      echo "Load gitlab utils finish"
  artifacts:
    paths:
      - gitlab_utils.tar
