applicationName: application
namespace: <test_bob>

image:
  registry: registry-example.com:5000

pod:
  cpu:
    limit: 250m
    request: 250m
  memory:
    limit: 1Gi
    request: 1Gi
  port: 8443

service:
  port: 8443
  deploy: false

route:
  deploy: false
  domain: example.com

certs:
  deploy: false
  itsi: <itsi>
  navigatorId: <navigator_id>
  projectName: <itsi_name>
  environment: Test
  changeNumber: N/A
  email: <email>
  mountPath: /etc/certs

hpa:
  deploy: false
  minPods: 1
  maxPods: 3
  cpuUsage: 80
  memoryUsage: 80

blb:
  deploy: false
