variables:
  ENV_NAME: dev
  APP_TRIGGER: httpdswag
  
httpd-swag-build:
  variables:
    BUILDER_IMAGE_NAME: $BUILDER_IMAGE_NODE_20
    APP: httpdswag
  stage: build
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/ci-image.yml'
    strategy: depend
    
httpd-swag-deploy:
  variables:
    APP: httpdswag
  stage: deploy
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/bcp-container-deploy.yml'
    strategy: depend
  only:
    variables:
      - $APP_TRIGGER == "ALL"
    
httpd-swag-reload:
  variables:
    APP: httpdswag
  stage: deploy
  trigger:
    include:
      - project: 'linfeng.song/gitlab-templates'
        file: 'templates/v1/bcp-container-reload.yml'
    strategy: depend
  only:
    variables:
      - $APP_TRIGGER == $APP
      