include:
  - project: 'dev/dev-java/gitlab_common'
    ref: master
    file: '/templates/v1/gitlab_ci-httpd.yml'

deploy:
  stage: deploy
  variables:
    CONTAINER_TRIGGER: httpd-swag
  trigger:
    project: 'dev/dev-java/service'
    branch: master

    