apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swag
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: {{ .Chart.Version }}
  name: swag
spec:            
  replicas: {{ .Values.swag.replicas }}
  selector:
    matchLabels:
      app: swag
  template:
    metadata:
      labels:
        app: swag
        name: swag
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: 1.0.0
    spec:
      containers:
      - image: "{{ .Values.swag.image.name }}:{{ .Values.swag.image.tag }}"
        imagePullPolicy: {{ .Values.swag.image.pullPolicy }}
        ports:
        - containerPort: 8080
          hostPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        name: swag
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: {{ .Values.swag.httpScheme }}
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
            scheme: {{ .Values.swag.httpScheme }}
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          privileged: false
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: persistent-volume
          mountPath: /home/app/swag/logs
          subPath: logs/$(POD_NAME}
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: swag
