{{- if .Values.blb.deploy }}
apiVersion: kctl.example.com/v1
kind: KctlLoadBalancer
metadata:
  name: "{{ .Values.applicationName }}-blb"
  namespace: {{ .Values.namespace | quote }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  route: "{{ .Values.applicationName }}-route"
{{ end }}